# Generated by Django 2.0 on 2017-12-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20171213_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='album',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='uploads/<django.db.models.fields.CharField>'),
        ),
    ]
