# Generated by Django 2.0 on 2017-12-28 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20171213_2314'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
